### PR TITLE
s3 support

### PR DESCRIPTION
**Pull request by jimisaacs**
Adds a simple s3 client
Adds a fs_s3.go that uses that client.
Makes config parsing allow for arbitrary things before the `?`

--- 

This is only half tested at the time of opening this PR.

### CODE REVIEW

**Comment by ije** [comment]
so fast! thanks @jimisaacs

**Comment by ije** [comment]
LGTM

**Comment by drkibitz** [comment]
FYI I didn't fully test that. Sorry I was planning to iterate a little more.

**Comment by jimisaacs** [comment]
@ije FYI, this still isn’t fully tested, was planning to iterate a bit more. Hope that is ok.

**Comment by ije** [comment]
no worries, we can improve it later, thanks 🙏

**Pull request merged**
